[workspace]

[package]
name = "pi"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
libm = "0.2.6"
slib = { path = "../../slib" }

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = true
panic = "abort"
