[workspace]
members = [
    "bootloader_server",
]

[workspace.package]
edition = "2021"

[package]
name = "onchip"
version = "0.0.0"
publish = false

[profile.release]
lto = true
codegen-units = 1
strip = true
panic = "abort"
