[workspace]

[package]
name = "bootloader_server"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bootloader = { path = "../../bootloader" }
slib = { path = "../../slib" }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"
