[build]
target = "riscv32i-unknown-none-elf"

[target.riscv32i-unknown-none-elf]
rustflags = [
    "-Clink-arg=-T../program.lds",
    "-Crelocation-model=pic",
    "-Ctarget-feature=+m",
    # TODO https://github.com/rust-lang/rust/issues/108853
    "-Zshare-generics=off",
]

[unstable]
build-std = ["core"]
