[build]
target = "riscv32i-unknown-none-elf"

[target.riscv32i-unknown-none-elf]
rustflags = [
    "-Clink-arg=-T../program.lds",
    "-Ctarget-feature=+m",
]

[unstable]
build-std = ["core", "panic_abort"]
build-std-features = ["panic_immediate_abort"]
