[build]
target = "riscv32i-unknown-none-elf"

[target.riscv32i-unknown-none-elf]
rustflags = [
    "-C", "link-arg=-T../program.lds",
    "-C", "relocation-model=pic",
    "-C", "target-feature=+m",
]

[unstable]
build-std = ["core"]
