[package]
name = "bootloader_client"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
bootloader = { path = "../../bootloader" }
clap2 = { version = "4.1.8", features = ["derive", "wrap_help"] }
shared = { path = "../../shared" }
